# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: '3'

tasks:
  build:
    dir: '{{.USER_WORKING_DIR}}'
    sources:
      - src/**/*
      - scripts/**/*
      - tsconfig*
    cmds:
      - rm -rf lua/neotest-playwright
      - tstl -p tsconfig.build.json {{.CLI_ARGS}}
      - cp src/util.lua lua/neotest-playwright/util.lua
      - cp -r src/consumers lua/neotest-playwright/consumers
      - tsx ./scripts/fix-require-paths.ts

  format:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - prettier --{{.ACTION | default "check"}} "**/*.{js,cjs,mjs,ts,cts,mts,md,yaml,yml,json,jsonc}"
